### ISSUE TITLE
Running the tests frequently hang. Fix tests or underlying problem with the code.

### ISSUE THREAD

**Issue by smootoo** [manahl/lockable-resources-plugin#4]
Always hangs on CircleCI and often locally. Seems worse with some of the PRs we have merged than current upstream master.

**Comment by smootoo** [comment]
Here is one example
```
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.jvnet.hudson.test.JenkinsRule.waitForMessage(JenkinsRule.java:1246)
	at org.jenkins.plugins.lockableresources.LockStepTest$19.evaluate(LockStepTest.java:735)
	at org.jvnet.hudson.test.RestartableJenkinsRule$3.evaluate(RestartableJenkinsRule.java:84)
	at org.jvnet.hudson.test.JenkinsRule$2.evaluate(JenkinsRule.java:534)
	at org.jvnet.hudson.test.RestartableJenkinsRule.run(RestartableJenkinsRule.java:100)
	at org.jvnet.hudson.test.RestartableJenkinsRule.access$100(RestartableJenkinsRule.java:30)
	at org.jvnet.hudson.test.RestartableJenkinsRule$1.evaluate(RestartableJenkinsRule.java:64)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

interoperabilityOnRestart(org.jenkins.plugins.lockableresources.LockStepTest)  Time elapsed: 1.453 sec  <<< FAILURE!
java.lang.AssertionError: tried to overwrite p #1 with p #1
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:472)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:448)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:356)
	at jenkins.model.lazy.LazyBuildMixIn.getBuildByNumber(LazyBuildMixIn.java:226)
	at org.jenkinsci.plugins.workflow.job.WorkflowJob.getBuildByNumber(WorkflowJob.java:215)
	at org.jenkins.plugins.lockableresources.LockStepTest$14.evaluate(LockStepTest.java:518)
	at org.jvnet.hudson.test.RestartableJenkinsRule$3.evaluate(RestartableJenkinsRule.java:84)
	at org.jvnet.hudson.test.JenkinsRule$2.evaluate(JenkinsRule.java:534)
	at org.jvnet.hudson.test.RestartableJenkinsRule.run(RestartableJenkinsRule.java:100)
	at org.jvnet.hudson.test.RestartableJenkinsRule.access$100(RestartableJenkinsRule.java:30)
	at org.jvnet.hudson.test.RestartableJenkinsRule$1.evaluate(RestartableJenkinsRule.java:64)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

Running InjectedTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.957 sec - in InjectedTest

Results :

Flaked tests: 
org.jenkins.plugins.lockableresources.LockStepTest.deleteRunningBuildNewBuildClearsLock(org.jenkins.plugins.lockableresources.LockStepTest)
  Run 1: LockStepTest.deleteRunningBuildNewBuildClearsLock » Interrupted sleep interrup...
  Run 2: PASS

org.jenkins.plugins.lockableresources.LockStepTest.interoperabilityOnRestart(org.jenkins.plugins.lockableresources.LockStepTest)
  Run 1: LockStepTest.interoperabilityOnRestart tried to overwrite p #1 with p #1
  Run 2: PASS
```
